# infra/base/task-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: default
  labels:
    app: task-service
spec:
  selector:
    app: task-service               # must match Deployment's pod labels
  ports:
  - protocol: TCP
    port: 8000                      # port other services use to reach this
    targetPort: 8000                # container's port
    nodePort: 30002                 # optional: for direct access from host
  type: NodePort                    # easiest for Minikube local access